name: taggables
version: 0.0.1
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
description: a derivative implementation of x-tag components in dart with a few differences
dependencies:
    browser: any
    hub: any
