name: taggables
version: 0.0.5
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
homepage: http://github.com/influx6/taggables.dart
description: a derivative implementation of x-tag components in dart with a few differences
dependencies:
    browser: any
    hub: any
    bass: any
#dependency_overrides:
#    hub:
#      path: ../hub
#    bass:
#      path: ../bass
